-- Generated SQL for AoE2 Civilizations
-- Generated on: 2025-10-29 12:06:32
-- Total civilizations: 50

INSERT INTO public.civilizations (name, description, image_url, display_order) VALUES
  ('Armenians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/armenians.png', 1),
  ('Aztecs', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/aztecs.png', 2),
  ('Bengalis', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/bengalis.png', 3),
  ('Berbers', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/berbers.png', 4),
  ('Bohemians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/bohemians.png', 5),
  ('Britons', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/britons.png', 6),
  ('Bulgarians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/bulgarians.png', 7),
  ('Burgundians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/burgundians.png', 8),
  ('Burmese', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/burmese.png', 9),
  ('Byzantines', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/byzantines.png', 10),
  ('Celts', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/celts.png', 11),
  ('Chinese', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/chinese.png', 12),
  ('Cumans', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/cumans.png', 13),
  ('Dravidians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/dravidians.png', 14),
  ('Ethiopians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/ethiopians.png', 15),
  ('Franks', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/franks.png', 16),
  ('Georgians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/georgians.png', 17),
  ('Goths', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/goths.png', 18),
  ('Gurjaras', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/gurjaras.png', 19),
  ('Huns', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/huns.png', 20),
  ('Incas', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/incas.png', 21),
  ('Indians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/indians.png', 22),
  ('Italians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/italians.png', 23),
  ('Japanese', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/japanese.png', 24),
  ('Jurchens', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/jurchens.png', 25),
  ('Khitans', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/khitans.png', 26),
  ('Khmer', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/khmer.png', 27),
  ('Koreans', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/koreans.png', 28),
  ('Lithuanians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/lithuanians.png', 29),
  ('Magyars', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/magyars.png', 30),
  ('Malay', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/malay.png', 31),
  ('Malians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/malians.png', 32),
  ('Mayans', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/mayans.png', 33),
  ('Mongols', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/mongols.png', 34),
  ('Persians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/persians.png', 35),
  ('Poles', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/poles.png', 36),
  ('Portuguese', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/portuguese.png', 37),
  ('Romans', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/romans.png', 38),
  ('Saracens', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/saracens.png', 39),
  ('Shu', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/shu.png', 40),
  ('Sicilians', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/sicilians.png', 41),
  ('Slavs', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/slavs.png', 42),
  ('Spanish', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/spanish.png', 43),
  ('Tatars', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/tatars.png', 44),
  ('Teutons', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/teutons.png', 45),
  ('Turks', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/turks.png', 46),
  ('Vietnamese', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/vietnamese.png', 47),
  ('Vikings', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/vikings.png', 48),
  ('Wei', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/wei.png', 49),
  ('Wu', 'To be decided', 'https://jcpkansfiogtpppvkpjs.supabase.co/storage/v1/object/public/civ-images/wu.png', 50)
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  display_order = EXCLUDED.display_order,
  updated_at = NOW();

